on:
  pull_request:
    paths: &paths
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/db-mariadb.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'

  push:
    branches: ['master']
    paths: *paths

name: db-mariadb

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: MariaDB ${{ matrix.mariadb }}

    strategy:
      matrix:
        php:
          - 8.5

        mariadb:
          - 10.4
          - 10.5
          - 10.6
          - 10.7
          - 10.8
          - 10.9
          - latest

        include:
          - php: 8.1
            mariadb: latest
          - php: 8.2
            mariadb: latest
          - php: 8.3
            mariadb: latest
          - php: 8.4
            mariadb: latest

    uses: yiisoft/actions/.github/workflows/db-mariadb.yml@master
    with:
      mariadb: ${{ matrix.mariadb }}
      php: >-
        [${{ matrix.php }}]

